spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: SmartEvent
  datasource:
    url: jdbc:postgresql://localhost:5432/smartevent
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      pool-name: SmartEventHikari
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 900000
    refresh-expiration-ms: 604800000

external:
  ticketmaster:
    api-key: ${TICKETMASTER_API_KEY:dev-ticketmaster-key}
    api-secret: ${TICKETMASTER_API_SECRET:dev-ticketmaster-secret}

ticketmaster:
  base-url: https://app.ticketmaster.com/discovery/v2
  api-key: ${TICKETMASTER_API_KEY:dev-ticketmaster-key}
